### ISSUE TITLE
ValueError: could not convert string to float:

### ISSUE THREAD

**Issue by VaticanCameos99** [pulimeng/DeepDrug3D#13]
Thanks for making your code public. Had a doubt:

I am using Ubuntu 20.04 

While running the voxelization.py file, I got a permission denied error for ./dligand-linux. I changed the permissions and next I see is this:

`Calculating of the binding site potential energy ./dligand-linux: error while loading shared libraries: libstdc++-libc6.2-2.so.3: cannot open shared object file: No such file or directory  
Traceback (most recent call last):  
  File "voxelization.py", line 83, in <module>  
    Vox3DBuilder().voxelization(opt.f, opt.a, opt.r, opt.n, opt.o, opt.shape)  
  File "voxelization.py", line 63, in voxelization  
    pocket_grid = Grid3DBuilder.build(pdb_path, aux_input_path, r, N, output_folder, shape)  
  File "/home/name/Downloads/Work/Name/DeepDrug3D/DataGeneration/build_grid.py", line 283, in build
    total_potE = potEnergy(new_site, 'dummy_mol2.mol2', output_trans_mol2_path)  
  File "/home/name/Downloads/Work/Name/DeepDrug3D/DataGeneration/build_grid.py", line 221, in potEnergy
    potEs = np.array([single_potEnergy(loc1, ld_type_list, mol2_in_string, protein_file) for loc1 in binding_site])  
  File "/home/name/Downloads/Work/Name/DeepDrug3D/DataGeneration/build_grid.py", line 221, in <listcomp>
    potEs = np.array([single_potEnergy(loc1, ld_type_list, mol2_in_string, protein_file) for loc1 in binding_site])  
  File "/home/name/Downloads/Work/Name/DeepDrug3D/DataGeneration/build_grid.py", line 205, in single_potEnergy  
    b = float(a)  
ValueError: could not convert string to float: `

Note: the value of a is derived from the out variable which turns out to be an empty string.

How do I resolve this error?

**Comment by pulimeng** [comment]
I think it could be the problem of the output of ./dligand-linux. Can you run ./dligand-linux separately on your file and see what is the output

**Comment by VaticanCameos99** [comment]
This gives the same error. `./dligand-linux: error while loading shared libraries: libstdc++-libc6.2-2.so.3: cannot open shared object file: No such file or directory`

**Comment by pulimeng** [comment]
I'm not sure what is the problem exactly. Did you try install the corresponding lib?

**Comment by VaticanCameos99** [comment]
I tried following the directions given here: https://community.progress.com/s/article/000055534 . But the corresponding library seems to be no longer existent.

**Comment by VaticanCameos99** [comment]
I tried this on my local  machine as well as on Colab. Same pattern of errors in both.
